import { RadarNode, RadarNetworkSummary, DiagnosticResult } from '@/types/radar';

export const ALL_38_DOPPLER_NODES: RadarNode[] = [
  // ── 1. Northern Himalayas & NCR (9 Nodes) ──
  {
    id: 'dwr-01',
    name: 'New Delhi Mausam Bhawan',
    code: 'DWR-DEL-MB',
    city: 'New Delhi',
    state: 'Delhi NCR',
    region: 'Northern Himalayas',
    lat: 28.5889,
    lng: 77.2215,
    elevationM: 216,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'VCP-21 Convective Volume Scan',
    status: 'ONLINE',
    latencyMs: 12.4,
    uptimePercent: 99.98,
    noiseFloorDbm: -112.5,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 46.5,
    zdrDb: 1.8,
    correlationCoeff: 0.98,
    kdpDegKm: 1.2,
    velocityMs: 14.5,
    azimuthDeg: 142,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 28,
    lastScanTime: 'Just now',
    scanStrategy: '10 Elevation Cuts (0.5° - 19.5°)',
  },
  {
    id: 'dwr-02',
    name: 'New Delhi Palam Airport',
    code: 'DWR-DEL-PAL',
    city: 'New Delhi',
    state: 'Delhi NCR',
    region: 'Northern Himalayas',
    lat: 28.5665,
    lng: 77.1031,
    elevationM: 237,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1200,
    vMaxMs: 64,
    operatingMode: 'Aviation Terminal Low-Level Windshear',
    status: 'STREAMING',
    latencyMs: 14.1,
    uptimePercent: 99.95,
    noiseFloorDbm: -114.1,
    calibrationOffsetDb: -0.01,
    reflectivityDbz: 38.2,
    zdrDb: 0.9,
    correlationCoeff: 0.99,
    kdpDegKm: 0.4,
    velocityMs: -8.2,
    azimuthDeg: 280,
    elevationDeg: 1.5,
    hydrometeorType: 'Light Rain / Drizzle',
    traineesConnected: 19,
    lastScanTime: 'Just now',
    scanStrategy: 'Rapid Sector Scan 30s Interval',
  },
  {
    id: 'dwr-03',
    name: 'Srinagar Pir Panjal Observatory',
    code: 'DWR-SXR-01',
    city: 'Srinagar',
    state: 'Jammu & Kashmir',
    region: 'Northern Himalayas',
    lat: 34.0837,
    lng: 74.7973,
    elevationM: 1585,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 1000,
    vMaxMs: 32,
    operatingMode: 'Western Disturbance Orographic Tracking',
    status: 'ONLINE',
    latencyMs: 18.2,
    uptimePercent: 99.89,
    noiseFloorDbm: -110.2,
    calibrationOffsetDb: 0.05,
    reflectivityDbz: 32.8,
    zdrDb: 0.3,
    correlationCoeff: 0.92,
    kdpDegKm: 0.8,
    velocityMs: 22.1,
    azimuthDeg: 65,
    elevationDeg: 2.0,
    hydrometeorType: 'Wet Snow / Melting Layer',
    traineesConnected: 14,
    lastScanTime: 'Just now',
    scanStrategy: 'High-Elevation Orographic Scan',
  },
  {
    id: 'dwr-04',
    name: 'Leh Ladakh High-Altitude Station',
    code: 'DWR-IXL-01',
    city: 'Leh',
    state: 'Ladakh UT',
    region: 'Northern Himalayas',
    lat: 34.1526,
    lng: 77.5771,
    elevationM: 3500,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 120,
    prfHz: 1100,
    vMaxMs: 36,
    operatingMode: 'Cloudburst & Glacial Telemetry',
    status: 'ONLINE',
    latencyMs: 21.6,
    uptimePercent: 99.78,
    noiseFloorDbm: -109.8,
    calibrationOffsetDb: 0.04,
    reflectivityDbz: 21.4,
    zdrDb: 0.1,
    correlationCoeff: 0.94,
    kdpDegKm: 0.2,
    velocityMs: 11.0,
    azimuthDeg: 195,
    elevationDeg: 3.5,
    hydrometeorType: 'Clear Air / Marine Boundary',
    traineesConnected: 11,
    lastScanTime: 'Just now',
    scanStrategy: 'Glacier Valley Profiling',
  },
  {
    id: 'dwr-05',
    name: 'Patiala Central Punjab Node',
    code: 'DWR-PAT-01',
    city: 'Patiala',
    state: 'Punjab',
    region: 'Northern Himalayas',
    lat: 30.3398,
    lng: 76.3869,
    elevationM: 250,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 900,
    vMaxMs: 40,
    operatingMode: 'Convective Squall & Fog Monitor',
    status: 'ONLINE',
    latencyMs: 13.9,
    uptimePercent: 99.92,
    noiseFloorDbm: -113.8,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 42.1,
    zdrDb: 1.4,
    correlationCoeff: 0.97,
    kdpDegKm: 0.9,
    velocityMs: 9.4,
    azimuthDeg: 310,
    elevationDeg: 0.8,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 16,
    lastScanTime: 'Just now',
    scanStrategy: 'Agricultural Agro-Met Volume Scan',
  },
  {
    id: 'dwr-06',
    name: 'Mukteshwar Kumaon Himalayas',
    code: 'DWR-MUK-01',
    city: 'Mukteshwar',
    state: 'Uttarakhand',
    region: 'Northern Himalayas',
    lat: 29.4722,
    lng: 79.6481,
    elevationM: 2171,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 1000,
    vMaxMs: 34,
    operatingMode: 'Cloudburst Nowcasting & Landslide Warning',
    status: 'NOWCASTING',
    latencyMs: 17.5,
    uptimePercent: 99.91,
    noiseFloorDbm: -111.4,
    calibrationOffsetDb: 0.03,
    reflectivityDbz: 54.2,
    zdrDb: 2.9,
    correlationCoeff: 0.96,
    kdpDegKm: 2.4,
    velocityMs: 27.8,
    azimuthDeg: 42,
    elevationDeg: 1.8,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 22,
    lastScanTime: 'Just now',
    scanStrategy: 'Rapid Orographic Cloudburst Sentinel',
  },
  {
    id: 'dwr-07',
    name: 'Kufri / Shimla Ridge',
    code: 'DWR-KUF-01',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    region: 'Northern Himalayas',
    lat: 31.0979,
    lng: 77.2678,
    elevationM: 2630,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 1000,
    vMaxMs: 32,
    operatingMode: 'Snowpack & Severe Storm Profiler',
    status: 'ONLINE',
    latencyMs: 16.8,
    uptimePercent: 99.88,
    noiseFloorDbm: -112.0,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 28.5,
    zdrDb: 0.4,
    correlationCoeff: 0.93,
    kdpDegKm: 0.3,
    velocityMs: -12.4,
    azimuthDeg: 110,
    elevationDeg: 2.2,
    hydrometeorType: 'Wet Snow / Melting Layer',
    traineesConnected: 15,
    lastScanTime: 'Just now',
    scanStrategy: 'Himalayan Ridge Surveillance',
  },
  {
    id: 'dwr-08',
    name: 'Surkanda Devi Tehri Garhwal',
    code: 'DWR-SUR-01',
    city: 'Tehri',
    state: 'Uttarakhand',
    region: 'Northern Himalayas',
    lat: 30.4143,
    lng: 78.2939,
    elevationM: 2756,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 1050,
    vMaxMs: 35,
    operatingMode: 'Char Dham Pilgrimage Cloudburst Shield',
    status: 'STREAMING',
    latencyMs: 19.3,
    uptimePercent: 99.94,
    noiseFloorDbm: -110.9,
    calibrationOffsetDb: -0.02,
    reflectivityDbz: 36.4,
    zdrDb: 1.1,
    correlationCoeff: 0.97,
    kdpDegKm: 0.7,
    velocityMs: 16.3,
    azimuthDeg: 220,
    elevationDeg: 2.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 18,
    lastScanTime: 'Just now',
    scanStrategy: 'Char Dham High-Risk Sector Mode',
  },
  {
    id: 'dwr-09',
    name: 'Jammu Tawi Base',
    code: 'DWR-JMU-01',
    city: 'Jammu',
    state: 'Jammu & Kashmir',
    region: 'Northern Himalayas',
    lat: 32.7266,
    lng: 74.857,
    elevationM: 327,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 950,
    vMaxMs: 33,
    operatingMode: 'Plains-Foothill Transition Scan',
    status: 'ONLINE',
    latencyMs: 15.2,
    uptimePercent: 99.9,
    noiseFloorDbm: -113.1,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 29.0,
    zdrDb: 0.6,
    correlationCoeff: 0.98,
    kdpDegKm: 0.3,
    velocityMs: 7.8,
    azimuthDeg: 350,
    elevationDeg: 1.0,
    hydrometeorType: 'Clear Air / Marine Boundary',
    traineesConnected: 12,
    lastScanTime: 'Just now',
    scanStrategy: 'Surveillance 250km PPI',
  },

  // ── 2. Coastal Bay of Bengal Network (9 Nodes) ──
  {
    id: 'dwr-10',
    name: 'Kolkata Alipore Met Centre',
    code: 'DWR-CCU-01',
    city: 'Kolkata',
    state: 'West Bengal',
    region: 'Bay of Bengal Coast',
    lat: 22.5312,
    lng: 88.3341,
    elevationM: 6,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Nor’wester (Kalbaisakhi) & Cyclone Tracking',
    status: 'ONLINE',
    latencyMs: 11.8,
    uptimePercent: 99.99,
    noiseFloorDbm: -114.8,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 51.4,
    zdrDb: 2.8,
    correlationCoeff: 0.97,
    kdpDegKm: 1.9,
    velocityMs: -31.5,
    azimuthDeg: 165,
    elevationDeg: 0.5,
    hydrometeorType: 'Severe Squall Line',
    traineesConnected: 34,
    lastScanTime: 'Just now',
    scanStrategy: 'Dual-Pol Full Volume Scan 6 min',
  },
  {
    id: 'dwr-11',
    name: 'Chennai Port Coastal S-Band',
    code: 'DWR-MAA-01',
    city: 'Chennai',
    state: 'Tamil Nadu',
    region: 'Bay of Bengal Coast',
    lat: 13.0827,
    lng: 80.2707,
    elevationM: 8,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Northeast Monsoon & Cyclone Warning',
    status: 'ONLINE',
    latencyMs: 12.1,
    uptimePercent: 99.98,
    noiseFloorDbm: -115.0,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 48.0,
    zdrDb: 2.1,
    correlationCoeff: 0.98,
    kdpDegKm: 1.4,
    velocityMs: 19.8,
    azimuthDeg: 88,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 30,
    lastScanTime: 'Just now',
    scanStrategy: 'Long-Range Cyclone Surveillance',
  },
  {
    id: 'dwr-12',
    name: 'Machilipatnam Cyclone Sentinel',
    code: 'DWR-MPT-01',
    city: 'Machilipatnam',
    state: 'Andhra Pradesh',
    region: 'Bay of Bengal Coast',
    lat: 16.1875,
    lng: 81.1389,
    elevationM: 4,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Krishna-Godavari Cyclone Eye Tracker',
    status: 'STREAMING',
    latencyMs: 14.5,
    uptimePercent: 99.96,
    noiseFloorDbm: -113.7,
    calibrationOffsetDb: -0.01,
    reflectivityDbz: 58.6,
    zdrDb: 3.4,
    correlationCoeff: 0.95,
    kdpDegKm: 3.1,
    velocityMs: 38.2,
    azimuthDeg: 125,
    elevationDeg: 0.5,
    hydrometeorType: 'Tropical Cyclone Spiral Band',
    traineesConnected: 25,
    lastScanTime: 'Just now',
    scanStrategy: 'Spiral Band Mesoscale Intercept',
  },
  {
    id: 'dwr-13',
    name: 'Visakhapatnam Dolphin’s Nose',
    code: 'DWR-VTZ-01',
    city: 'Visakhapatnam',
    state: 'Andhra Pradesh',
    region: 'Bay of Bengal Coast',
    lat: 17.6868,
    lng: 83.2185,
    elevationM: 160,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Deep Maritime Severe Convection',
    status: 'ONLINE',
    latencyMs: 13.6,
    uptimePercent: 99.97,
    noiseFloorDbm: -114.2,
    calibrationOffsetDb: 0.03,
    reflectivityDbz: 44.7,
    zdrDb: 1.7,
    correlationCoeff: 0.98,
    kdpDegKm: 1.1,
    velocityMs: -15.6,
    azimuthDeg: 95,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 21,
    lastScanTime: 'Just now',
    scanStrategy: 'Dual-Pol Doppler Velocity De-aliasing',
  },
  {
    id: 'dwr-14',
    name: 'Paradip Port Coastal Radar',
    code: 'DWR-PRD-01',
    city: 'Paradip',
    state: 'Odisha',
    region: 'Bay of Bengal Coast',
    lat: 20.2644,
    lng: 86.6719,
    elevationM: 5,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Odisha Cyclone Early Warning Radar',
    status: 'ONLINE',
    latencyMs: 12.9,
    uptimePercent: 99.98,
    noiseFloorDbm: -114.9,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 49.3,
    zdrDb: 2.3,
    correlationCoeff: 0.98,
    kdpDegKm: 1.6,
    velocityMs: 24.1,
    azimuthDeg: 140,
    elevationDeg: 0.5,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 26,
    lastScanTime: 'Just now',
    scanStrategy: 'Coastal High-Reflectivity Surveillance',
  },
  {
    id: 'dwr-15',
    name: 'Gopalpur on Sea',
    code: 'DWR-GOP-01',
    city: 'Gopalpur',
    state: 'Odisha',
    region: 'Bay of Bengal Coast',
    lat: 19.2612,
    lng: 84.9082,
    elevationM: 12,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Southern Odisha Cyclone Landfall Gate',
    status: 'ONLINE',
    latencyMs: 14.0,
    uptimePercent: 99.95,
    noiseFloorDbm: -114.0,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 37.1,
    zdrDb: 1.0,
    correlationCoeff: 0.99,
    kdpDegKm: 0.5,
    velocityMs: 10.2,
    azimuthDeg: 115,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 17,
    lastScanTime: 'Just now',
    scanStrategy: 'S-Band Dual-Pol Polarimetric Grid',
  },
  {
    id: 'dwr-16',
    name: 'Karaikal Coastal Observatory',
    code: 'DWR-KRK-01',
    city: 'Karaikal',
    state: 'Puducherry UT',
    region: 'Bay of Bengal Coast',
    lat: 10.9254,
    lng: 79.838,
    elevationM: 7,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Cauvery Delta & Palk Strait Scan',
    status: 'ONLINE',
    latencyMs: 13.4,
    uptimePercent: 99.94,
    noiseFloorDbm: -113.9,
    calibrationOffsetDb: -0.01,
    reflectivityDbz: 41.5,
    zdrDb: 1.3,
    correlationCoeff: 0.98,
    kdpDegKm: 0.8,
    velocityMs: 13.7,
    azimuthDeg: 72,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 16,
    lastScanTime: 'Just now',
    scanStrategy: 'Palk Strait Convective Scan',
  },
  {
    id: 'dwr-17',
    name: 'Sriharikota ISRO SDSC Spaceport',
    code: 'DWR-SHAR-01',
    city: 'Sriharikota',
    state: 'Andhra Pradesh',
    region: 'Bay of Bengal Coast',
    lat: 13.7199,
    lng: 80.2305,
    elevationM: 10,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 800,
    vMaxMs: 52,
    operatingMode: 'Launch Vehicle Weather Clear-Go Radar',
    status: 'STREAMING',
    latencyMs: 11.2,
    uptimePercent: 99.99,
    noiseFloorDbm: -116.1,
    calibrationOffsetDb: 0.00,
    reflectivityDbz: 30.5,
    zdrDb: 0.5,
    correlationCoeff: 0.99,
    kdpDegKm: 0.3,
    velocityMs: -5.4,
    azimuthDeg: 80,
    elevationDeg: 1.0,
    hydrometeorType: 'Light Rain / Drizzle',
    traineesConnected: 24,
    lastScanTime: 'Just now',
    scanStrategy: 'Ultra-High Precision Launch Window VCP',
  },
  {
    id: 'dwr-18',
    name: 'Port Blair Andaman Outpost',
    code: 'DWR-IXZ-01',
    city: 'Port Blair',
    state: 'Andaman & Nicobar',
    region: 'Island Outposts',
    lat: 11.6234,
    lng: 92.7265,
    elevationM: 16,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Southeast Bay Cyclone Genesis Monitor',
    status: 'ONLINE',
    latencyMs: 23.4,
    uptimePercent: 99.91,
    noiseFloorDbm: -114.5,
    calibrationOffsetDb: 0.03,
    reflectivityDbz: 53.0,
    zdrDb: 2.7,
    correlationCoeff: 0.97,
    kdpDegKm: 2.1,
    velocityMs: 29.5,
    azimuthDeg: 210,
    elevationDeg: 0.5,
    hydrometeorType: 'Tropical Cyclone Spiral Band',
    traineesConnected: 19,
    lastScanTime: 'Just now',
    scanStrategy: 'Tropical Cyclone Genesis Sentinel',
  },

  // ── 3. Arabian Sea Coast & Western India (7 Nodes) ──
  {
    id: 'dwr-19',
    name: 'Mumbai Colaba Coastal S-Band',
    code: 'DWR-BOM-COL',
    city: 'Mumbai',
    state: 'Maharashtra',
    region: 'Arabian Sea Coast',
    lat: 18.9067,
    lng: 72.8147,
    elevationM: 15,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Urban Flash Flood & Offshore Squall Shield',
    status: 'ONLINE',
    latencyMs: 12.0,
    uptimePercent: 99.98,
    noiseFloorDbm: -114.7,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 56.8,
    zdrDb: 3.2,
    correlationCoeff: 0.96,
    kdpDegKm: 2.8,
    velocityMs: -34.2,
    azimuthDeg: 255,
    elevationDeg: 0.5,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 38,
    lastScanTime: 'Just now',
    scanStrategy: 'Urban Flash Flood 3-min Rapid Scan',
  },
  {
    id: 'dwr-20',
    name: 'Mumbai Veravali Hill C-Band',
    code: 'DWR-BOM-VER',
    city: 'Mumbai',
    state: 'Maharashtra',
    region: 'Arabian Sea Coast',
    lat: 19.1232,
    lng: 72.8711,
    elevationM: 95,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1200,
    vMaxMs: 64,
    operatingMode: 'Suburban Nowcasting & Microburst Alert',
    status: 'STREAMING',
    latencyMs: 13.1,
    uptimePercent: 99.96,
    noiseFloorDbm: -113.6,
    calibrationOffsetDb: -0.02,
    reflectivityDbz: 48.9,
    zdrDb: 2.0,
    correlationCoeff: 0.98,
    kdpDegKm: 1.5,
    velocityMs: 18.9,
    azimuthDeg: 180,
    elevationDeg: 1.2,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 21,
    lastScanTime: 'Just now',
    scanStrategy: 'Microburst Velocity Azimuth Display',
  },
  {
    id: 'dwr-21',
    name: 'Goa Panaji Altinho Hill',
    code: 'DWR-GOI-01',
    city: 'Panaji',
    state: 'Goa',
    region: 'Arabian Sea Coast',
    lat: 15.4989,
    lng: 73.8278,
    elevationM: 60,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Western Ghats Orographic Convective Gate',
    status: 'ONLINE',
    latencyMs: 14.8,
    uptimePercent: 99.94,
    noiseFloorDbm: -114.1,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 43.6,
    zdrDb: 1.6,
    correlationCoeff: 0.98,
    kdpDegKm: 1.0,
    velocityMs: 12.8,
    azimuthDeg: 240,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 18,
    lastScanTime: 'Just now',
    scanStrategy: 'Orographic Enhancement VCP',
  },
  {
    id: 'dwr-22',
    name: 'Kochi Naval & Met Base',
    code: 'DWR-COK-01',
    city: 'Kochi',
    state: 'Kerala',
    region: 'Arabian Sea Coast',
    lat: 9.9312,
    lng: 76.2673,
    elevationM: 4,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Southwest Monsoon Inset & Maritime Squalls',
    status: 'ONLINE',
    latencyMs: 13.7,
    uptimePercent: 99.97,
    noiseFloorDbm: -114.6,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 50.1,
    zdrDb: 2.4,
    correlationCoeff: 0.97,
    kdpDegKm: 1.8,
    velocityMs: 26.3,
    azimuthDeg: 260,
    elevationDeg: 0.5,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 27,
    lastScanTime: 'Just now',
    scanStrategy: 'Monsoon Surge Polarimetric Detection',
  },
  {
    id: 'dwr-23',
    name: 'Thiruvananthapuram VSSC',
    code: 'DWR-TRV-01',
    city: 'Thiruvananthapuram',
    state: 'Kerala',
    region: 'Arabian Sea Coast',
    lat: 8.5241,
    lng: 76.9366,
    elevationM: 20,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1200,
    vMaxMs: 64,
    operatingMode: 'Equatorial Indian Ocean Convective Profiling',
    status: 'ONLINE',
    latencyMs: 14.3,
    uptimePercent: 99.95,
    noiseFloorDbm: -113.8,
    calibrationOffsetDb: -0.01,
    reflectivityDbz: 39.4,
    zdrDb: 1.2,
    correlationCoeff: 0.99,
    kdpDegKm: 0.6,
    velocityMs: -9.8,
    azimuthDeg: 190,
    elevationDeg: 1.0,
    hydrometeorType: 'Light Rain / Drizzle',
    traineesConnected: 19,
    lastScanTime: 'Just now',
    scanStrategy: 'Equatorial Wave Sentinel VCP',
  },
  {
    id: 'dwr-24',
    name: 'Bhuj Kutch Border Outpost',
    code: 'DWR-BHJ-01',
    city: 'Bhuj',
    state: 'Gujarat',
    region: 'Arabian Sea Coast',
    lat: 23.242,
    lng: 69.6669,
    elevationM: 110,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Rann of Kutch & Arabian Cyclone Radar',
    status: 'ONLINE',
    latencyMs: 15.6,
    uptimePercent: 99.92,
    noiseFloorDbm: -114.0,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 22.8,
    zdrDb: 0.2,
    correlationCoeff: 0.99,
    kdpDegKm: 0.1,
    velocityMs: 6.2,
    azimuthDeg: 280,
    elevationDeg: 0.5,
    hydrometeorType: 'Clear Air / Marine Boundary',
    traineesConnected: 14,
    lastScanTime: 'Just now',
    scanStrategy: 'Surveillance 500km Long Range',
  },
  {
    id: 'dwr-25',
    name: 'Veraval Saurashtra Coast',
    code: 'DWR-VRV-01',
    city: 'Veraval',
    state: 'Gujarat',
    region: 'Arabian Sea Coast',
    lat: 20.9077,
    lng: 70.3678,
    elevationM: 8,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Saurashtra Coast Deep Storm Gate',
    status: 'ONLINE',
    latencyMs: 16.1,
    uptimePercent: 99.93,
    noiseFloorDbm: -113.9,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 34.2,
    zdrDb: 0.8,
    correlationCoeff: 0.98,
    kdpDegKm: 0.4,
    velocityMs: -14.1,
    azimuthDeg: 215,
    elevationDeg: 0.5,
    hydrometeorType: 'Light Rain / Drizzle',
    traineesConnected: 15,
    lastScanTime: 'Just now',
    scanStrategy: 'Coastal Doppler Surveillance VCP',
  },

  // ── 4. Central India & Indo-Gangetic Plains (9 Nodes) ──
  {
    id: 'dwr-26',
    name: 'Jaipur Met Centre S-Band',
    code: 'DWR-JPR-01',
    city: 'Jaipur',
    state: 'Rajasthan',
    region: 'Central & Plains',
    lat: 26.9124,
    lng: 75.7873,
    elevationM: 431,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Dust Storm (Andhi) & Convective Cell Tracker',
    status: 'ONLINE',
    latencyMs: 12.8,
    uptimePercent: 99.96,
    noiseFloorDbm: -114.4,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 35.6,
    zdrDb: 0.7,
    correlationCoeff: 0.96,
    kdpDegKm: 0.5,
    velocityMs: 17.4,
    azimuthDeg: 290,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 20,
    lastScanTime: 'Just now',
    scanStrategy: 'Semi-Arid Convective Cloud Scan',
  },
  {
    id: 'dwr-27',
    name: 'Bhopal Central Met Observatory',
    code: 'DWR-BPL-01',
    city: 'Bhopal',
    state: 'Madhya Pradesh',
    region: 'Central & Plains',
    lat: 23.2599,
    lng: 77.4126,
    elevationM: 527,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1000,
    vMaxMs: 42,
    operatingMode: 'Monsoon Depression Overland Path Tracker',
    status: 'ONLINE',
    latencyMs: 13.5,
    uptimePercent: 99.97,
    noiseFloorDbm: -114.1,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 47.3,
    zdrDb: 2.1,
    correlationCoeff: 0.98,
    kdpDegKm: 1.3,
    velocityMs: 11.8,
    azimuthDeg: 135,
    elevationDeg: 0.8,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 22,
    lastScanTime: 'Just now',
    scanStrategy: 'Overland Depression Volumetric Scan',
  },
  {
    id: 'dwr-28',
    name: 'Indore Devi Ahilya Node',
    code: 'DWR-IDR-01',
    city: 'Indore',
    state: 'Madhya Pradesh',
    region: 'Central & Plains',
    lat: 22.7196,
    lng: 75.8577,
    elevationM: 553,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1000,
    vMaxMs: 42,
    operatingMode: 'Malwa Plateau Convection & Hail Detector',
    status: 'STREAMING',
    latencyMs: 14.1,
    uptimePercent: 99.94,
    noiseFloorDbm: -113.7,
    calibrationOffsetDb: -0.01,
    reflectivityDbz: 62.4,
    zdrDb: 0.1,
    correlationCoeff: 0.88,
    kdpDegKm: 3.8,
    velocityMs: -28.9,
    azimuthDeg: 340,
    elevationDeg: 1.5,
    hydrometeorType: 'Hail Core / Graupel',
    traineesConnected: 25,
    lastScanTime: 'Just now',
    scanStrategy: 'Severe Hail Detection Dual-Pol Algorithm',
  },
  {
    id: 'dwr-29',
    name: 'Nagpur Central Hub S-Band',
    code: 'DWR-NAG-01',
    city: 'Nagpur',
    state: 'Maharashtra',
    region: 'Central & Plains',
    lat: 21.1458,
    lng: 79.0882,
    elevationM: 310,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Heart-of-India National Triangulation Anchor',
    status: 'ONLINE',
    latencyMs: 11.5,
    uptimePercent: 99.99,
    noiseFloorDbm: -115.2,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 41.8,
    zdrDb: 1.5,
    correlationCoeff: 0.98,
    kdpDegKm: 0.9,
    velocityMs: 8.3,
    azimuthDeg: 170,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 31,
    lastScanTime: 'Just now',
    scanStrategy: 'National Composite Triangulation Master',
  },
  {
    id: 'dwr-30',
    name: 'Lucknow Amausi Airport',
    code: 'DWR-LKO-01',
    city: 'Lucknow',
    state: 'Uttar Pradesh',
    region: 'Central & Plains',
    lat: 26.7606,
    lng: 80.8893,
    elevationM: 123,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1200,
    vMaxMs: 64,
    operatingMode: 'Gangetic Basin Squall & Thunderstorm Watch',
    status: 'ONLINE',
    latencyMs: 12.6,
    uptimePercent: 99.95,
    noiseFloorDbm: -114.0,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 45.2,
    zdrDb: 1.9,
    correlationCoeff: 0.98,
    kdpDegKm: 1.2,
    velocityMs: 15.1,
    azimuthDeg: 210,
    elevationDeg: 0.8,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 23,
    lastScanTime: 'Just now',
    scanStrategy: 'Gangetic Plain Mesoscale Convection',
  },
  {
    id: 'dwr-31',
    name: 'Patna Met Centre C-Band',
    code: 'DWR-PAT-02',
    city: 'Patna',
    state: 'Bihar',
    region: 'Central & Plains',
    lat: 25.5941,
    lng: 85.1376,
    elevationM: 53,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1000,
    vMaxMs: 44,
    operatingMode: 'Lightning & Flash Flood Nowcast Gateway',
    status: 'ONLINE',
    latencyMs: 13.8,
    uptimePercent: 99.96,
    noiseFloorDbm: -113.9,
    calibrationOffsetDb: 0.00,
    reflectivityDbz: 53.7,
    zdrDb: 2.6,
    correlationCoeff: 0.97,
    kdpDegKm: 2.0,
    velocityMs: -22.4,
    azimuthDeg: 78,
    elevationDeg: 0.8,
    hydrometeorType: 'Severe Squall Line',
    traineesConnected: 29,
    lastScanTime: 'Just now',
    scanStrategy: 'Lightning Risk Convective Profiling',
  },
  {
    id: 'dwr-32',
    name: 'Ranchi Birsa Munda Node',
    code: 'DWR-IXR-01',
    city: 'Ranchi',
    state: 'Jharkhand',
    region: 'Central & Plains',
    lat: 23.3441,
    lng: 85.3096,
    elevationM: 651,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1000,
    vMaxMs: 44,
    operatingMode: 'Chota Nagpur Plateau Thunderstorm Tracking',
    status: 'ONLINE',
    latencyMs: 14.6,
    uptimePercent: 99.93,
    noiseFloorDbm: -113.5,
    calibrationOffsetDb: 0.03,
    reflectivityDbz: 49.0,
    zdrDb: 2.2,
    correlationCoeff: 0.98,
    kdpDegKm: 1.5,
    velocityMs: 18.2,
    azimuthDeg: 160,
    elevationDeg: 1.0,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 17,
    lastScanTime: 'Just now',
    scanStrategy: 'Plateau Orographic Convection VCP',
  },
  {
    id: 'dwr-33',
    name: 'Hyderabad Begumpet Met Centre',
    code: 'DWR-HYD-01',
    city: 'Hyderabad',
    state: 'Telangana',
    region: 'Central & Plains',
    lat: 17.4526,
    lng: 78.4721,
    elevationM: 536,
    band: 'S-Band',
    frequencyGhz: '2.8 GHz',
    peakPowerKw: 750,
    antennaDiameterM: 8.5,
    beamWidthDeg: 0.95,
    maxRangeKm: 500,
    prfHz: 600,
    vMaxMs: 48,
    operatingMode: 'Deccan Plateau Severe Convection Shield',
    status: 'ONLINE',
    latencyMs: 12.2,
    uptimePercent: 99.98,
    noiseFloorDbm: -114.9,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 42.6,
    zdrDb: 1.6,
    correlationCoeff: 0.98,
    kdpDegKm: 0.9,
    velocityMs: 10.5,
    azimuthDeg: 220,
    elevationDeg: 0.5,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 28,
    lastScanTime: 'Just now',
    scanStrategy: 'Volumetric Dual-Pol 500km Range',
  },
  {
    id: 'dwr-34',
    name: 'Bengaluru Karnataka Node',
    code: 'DWR-BLR-01',
    city: 'Bengaluru',
    state: 'Karnataka',
    region: 'Central & Plains',
    lat: 12.9716,
    lng: 77.5946,
    elevationM: 920,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1200,
    vMaxMs: 64,
    operatingMode: 'Urban Aviation & Thunderstorm Nowcasting',
    status: 'STREAMING',
    latencyMs: 11.9,
    uptimePercent: 99.97,
    noiseFloorDbm: -114.5,
    calibrationOffsetDb: -0.01,
    reflectivityDbz: 46.1,
    zdrDb: 1.8,
    correlationCoeff: 0.99,
    kdpDegKm: 1.2,
    velocityMs: -16.4,
    azimuthDeg: 300,
    elevationDeg: 0.8,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 33,
    lastScanTime: 'Just now',
    scanStrategy: 'High-Resolution Urban Ingress VCP',
  },

  // ── 5. Northeast India Network (3 Nodes) ──
  {
    id: 'dwr-35',
    name: 'Agartala Tripura International Border',
    code: 'DWR-IXA-01',
    city: 'Agartala',
    state: 'Tripura',
    region: 'Northeast India',
    lat: 23.8315,
    lng: 91.2868,
    elevationM: 15,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1000,
    vMaxMs: 44,
    operatingMode: 'Transboundary Severe Storm & Squall Profiler',
    status: 'ONLINE',
    latencyMs: 16.4,
    uptimePercent: 99.94,
    noiseFloorDbm: -113.8,
    calibrationOffsetDb: 0.02,
    reflectivityDbz: 52.3,
    zdrDb: 2.5,
    correlationCoeff: 0.97,
    kdpDegKm: 1.9,
    velocityMs: 23.6,
    azimuthDeg: 130,
    elevationDeg: 0.8,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 18,
    lastScanTime: 'Just now',
    scanStrategy: 'Transboundary Convective Alert Mode',
  },
  {
    id: 'dwr-36',
    name: 'Mohanbari Upper Assam Base',
    code: 'DWR-MHB-01',
    city: 'Dibrugarh',
    state: 'Assam',
    region: 'Northeast India',
    lat: 27.4728,
    lng: 94.912,
    elevationM: 108,
    band: 'C-Band',
    frequencyGhz: '5.6 GHz',
    peakPowerKw: 250,
    antennaDiameterM: 4.2,
    beamWidthDeg: 1.0,
    maxRangeKm: 250,
    prfHz: 1000,
    vMaxMs: 44,
    operatingMode: 'Brahmaputra Valley Flood & Storm Sentinel',
    status: 'ONLINE',
    latencyMs: 17.8,
    uptimePercent: 99.92,
    noiseFloorDbm: -113.4,
    calibrationOffsetDb: 0.01,
    reflectivityDbz: 44.0,
    zdrDb: 1.7,
    correlationCoeff: 0.98,
    kdpDegKm: 1.1,
    velocityMs: -11.5,
    azimuthDeg: 45,
    elevationDeg: 0.8,
    hydrometeorType: 'Moderate Stratiform Rain',
    traineesConnected: 20,
    lastScanTime: 'Just now',
    scanStrategy: 'Brahmaputra Valley Riverine VCP',
  },
  {
    id: 'dwr-37',
    name: 'Cherrapunji Sohra Orographic Radar',
    code: 'DWR-SHR-01',
    city: 'Cherrapunji',
    state: 'Meghalaya',
    region: 'Northeast India',
    lat: 25.2986,
    lng: 91.7303,
    elevationM: 1430,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 1200,
    vMaxMs: 38,
    operatingMode: 'World Highest Rainfall Orographic Hydrometeor Profiler',
    status: 'NOWCASTING',
    latencyMs: 19.1,
    uptimePercent: 99.96,
    noiseFloorDbm: -110.8,
    calibrationOffsetDb: 0.04,
    reflectivityDbz: 64.8,
    zdrDb: 3.9,
    correlationCoeff: 0.95,
    kdpDegKm: 4.6,
    velocityMs: 36.4,
    azimuthDeg: 190,
    elevationDeg: 1.8,
    hydrometeorType: 'Heavy Convective Rain',
    traineesConnected: 29,
    lastScanTime: 'Just now',
    scanStrategy: 'Extreme Orographic Rain Quantification',
  },

  // ── 6. Himalayan Northern Gateway (1 Node) ──
  {
    id: 'dwr-38',
    name: 'Banihal Top Pir Panjal Pass',
    code: 'DWR-BNH-01',
    city: 'Banihal',
    state: 'Jammu & Kashmir',
    region: 'Northern Himalayas',
    lat: 33.4862,
    lng: 75.2014,
    elevationM: 2832,
    band: 'X-Band',
    frequencyGhz: '9.4 GHz',
    peakPowerKw: 50,
    antennaDiameterM: 2.4,
    beamWidthDeg: 1.25,
    maxRangeKm: 150,
    prfHz: 1100,
    vMaxMs: 36,
    operatingMode: 'Highway Tunnel & Avalanche Early Warning Radar',
    status: 'ONLINE',
    latencyMs: 18.7,
    uptimePercent: 99.87,
    noiseFloorDbm: -111.1,
    calibrationOffsetDb: 0.03,
    reflectivityDbz: 31.0,
    zdrDb: 0.5,
    correlationCoeff: 0.94,
    kdpDegKm: 0.4,
    velocityMs: 19.2,
    azimuthDeg: 330,
    elevationDeg: 2.8,
    hydrometeorType: 'Wet Snow / Melting Layer',
    traineesConnected: 16,
    lastScanTime: 'Just now',
    scanStrategy: 'Avalanche & Blizzard High-Resolution Cut',
  },
];

export function getNetworkSummary(): RadarNetworkSummary {
  const total = ALL_38_DOPPLER_NODES.length;
  const online = ALL_38_DOPPLER_NODES.filter((n) => n.status === 'ONLINE' || n.status === 'STREAMING' || n.status === 'NOWCASTING').length;
  const streaming = ALL_38_DOPPLER_NODES.filter((n) => n.status === 'STREAMING').length;
  const nowcasting = ALL_38_DOPPLER_NODES.filter((n) => n.status === 'NOWCASTING').length;
  const avgLat = Number((ALL_38_DOPPLER_NODES.reduce((acc, n) => acc + n.latencyMs, 0) / total).toFixed(1));
  const activeTrainees = ALL_38_DOPPLER_NODES.reduce((acc, n) => acc + n.traineesConnected, 0);

  return {
    totalNodes: total,
    onlineNodes: online,
    streamingNodes: streaming,
    nowcastingAlerts: nowcasting,
    avgLatencyMs: avgLat,
    p99LatencyMs: 19.8,
    nationalCoverageSqKm: 3287263,
    telemetryThroughputMbPerSec: 284.5,
    activeTraineeObservers: activeTrainees,
    lastSyncTimestamp: new Date().toISOString(),
  };
}

export function runNodeDiagnostics(nodeId: string, testName: string): DiagnosticResult {
  const node = ALL_38_DOPPLER_NODES.find((n) => n.id === nodeId) || ALL_38_DOPPLER_NODES[0];
  
  const snr = Number((34.5 + Math.random() * 4).toFixed(1));
  const zdrBias = Number((0.01 + (Math.random() - 0.5) * 0.04).toFixed(3));
  const azimuthErr = Number(((Math.random() - 0.5) * 0.08).toFixed(3));
  const waveguideLoss = Number((0.42 + Math.random() * 0.05).toFixed(2));

  return {
    nodeId: node.id,
    testName,
    passed: true,
    timestamp: new Date().toISOString(),
    details: {
      snrDb: snr,
      nyquistDealiased: true,
      txPowerKw: node.peakPowerKw,
      zdrBiasDb: zdrBias,
      azimuthAlignmentErrorDeg: azimuthErr,
      waveguideLossDb: waveguideLoss,
    },
    log: [
      `[INIT] Connecting to Radar Telemetry Socket at ${node.code}...`,
      `[AUTH] Authenticated via Mission Mausam Telemetry Key (TLS 1.3, Latency ${node.latencyMs}ms)`,
      `[TX] Transmitter Peak Power verified: ${node.peakPowerKw} kW at ${node.frequencyGhz}`,
      `[CALIB] Differential Reflectivity (ZDR) solar calibration offset: ${zdrBias} dB (Tolerance ±0.1 dB: PASS)`,
      `[DOPPLER] Nyquist velocity fold check (V_max = ±${node.vMaxMs} m/s) with 4-phase PRF de-aliasing: 0 aliased pixels detected`,
      `[RECEIVER] Noise floor: ${node.noiseFloorDbm} dBm | Signal-to-Noise Ratio (SNR): ${snr} dB`,
      `[DUAL-POL] Correlation Coefficient (CC) baseline check: ρ_HV = ${node.correlationCoeff} (Valid hydrometeor echo verified)`,
      `[STREAM] 100% telemetry packets ACKed to National MoES Supercomputing Cluster (Pratyush/Mihir)`,
      `[RESULT] ✔ Radar Station ${node.name} (${node.code}) FULLY OPERATIONAL. All 38 Nodes Synchronized.`,
    ],
  };
}
